import addr from './addr.png'
import bookStore from './bookStore.png'
import cafe from './cafe.png'
import drug from './drug.png'
import home from './home.png'
import homeIcon from './homeIcon.png'
import hospIcon from './hospIcon.png'
import normal from './normal.png'
import phoneB from './phoneB.png'
import recom from './recom.png'
import review from './review.png'
import selected from './selected.png'
import red from './red.png'
import favStar from './favStar.png'
import storeIcon from './store.png'
import hotelIcon from './hotelIcon.png'
import chinaIcon from './chinaFoodIcon.png'
export {chinaIcon,hotelIcon,addr,bookStore,favStar,red,cafe,drug,home,homeIcon,
    hospIcon,normal,phoneB,recom,review,selected,storeIcon}